### ISSUE TITLE
Not working under IE11

### ISSUE THREAD

**Issue by kevincaradant** [eemeli/dot-properties#7]
Hi

When I want to use your lib (parse function) under IE11, i got this following issue:
![image](https://user-images.githubusercontent.com/6093175/81073839-813c7000-8ee8-11ea-8da2-8bc5f2f7f6e6.png)

Ex: 
```
import { parse } from 'dot-properties';
const properties = parse("toto=ok");
```

Do you have any idea why ? Otherwise FF / Chrome works well

Thank you in advance

Regards

**Comment by eemeli** [comment]
It's stumbling on some JS syntax that it doesn't understand. You'll probably need to transpile the library with e.g. `@babel/preset-env` to get it to work in IE11.

**Comment by eemeli** [comment]
Closing as answered.
